### Question 1 [2%] Implementing LD score regression

In [11]:
import pandas as pd

In [12]:
LD_pearson_corr = pd.read_csv('data/LD.csv', index_col=0)

In [13]:
beta_marg = pd.read_csv('data/beta_marginal.csv', index_col=0)

In [14]:
LD_pearson_corr

,rs9518832,rs970028,rs12866357,rs9518903,rs9518907,rs9518940,rs9518943,rs9300794,rs9586099,rs1158176,...,rs12004116,rs10781386,rs10119153,rs1936285,rs12685440,rs17785193,rs6560554,rs1361856,rs1361857,rs1361858
rs9518832,0.999000,-0.647595,0.528240,-0.658121,-0.646243,-0.647858,-0.154406,0.847165,-0.648272,0.552677,...,0.008973,-0.011053,0.054921,0.058127,0.033414,-0.032973,-0.023526,0.005402,0.004761,-0.003334
rs970028,-0.647595,0.999000,-0.409308,0.956043,0.997054,0.994144,-0.431340,-0.689275,0.998028,-0.567007,...,0.000139,0.046088,-0.013413,-0.018185,-0.018804,-0.003368,-0.018899,0.021746,0.001465,0.007506
rs12866357,0.528240,-0.409308,0.999000,-0.430109,-0.408672,-0.402608,-0.135176,0.577297,-0.409626,0.313646,...,-0.013543,-0.005163,0.071111,0.072883,0.048066,-0.031056,-0.018028,0.034910,0.040066,0.031143
rs9518903,-0.658121,0.956043,-0.430109,0.999000,0.958079,0.950806,-0.458652,-0.697505,0.955032,-0.505016,...,0.000919,0.039405,-0.012052,-0.016538,-0.025780,-0.019289,-0.029027,0.027833,0.001681,0.005593
rs9518907,-0.646243,0.997054,-0.408672,0.958079,0.999000,0.992196,-0.430434,-0.688063,0.996088,-0.565783,...,0.001113,0.048371,-0.011241,-0.016031,-0.018444,-0.006520,-0.018030,0.024149,0.004098,0.008060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
rs17785193,-0.032973,-0.003368,-0.031056,-0.019289,-0.006520,-0.001655,0.036886,-0.018916,-0.003838,-0.042768,...,0.336696,0.045058,-0.156078,-0.154978,0.373735,0.999000,0.924057,-0.156567,0.311690,0.352732
rs6560554,-0.023526,-0.018899,-0.018028,-0.029027,-0.018030,-0.016807,0.030973,-0.000108,-0.019333,-0.035660,...,0.377046,0.049715,-0.161920,-0.160869,0.347391,0.924057,0.999000,-0.159996,0.344827,0.346324
rs1361856,0.005402,0.021746,0.034910,0.027833,0.024149,0.020495,-0.031700,-0.006015,0.022834,0.012648,...,-0.089486,0.178569,0.848165,0.851054,0.713453,-0.156567,-0.159996,0.999000,0.797607,0.769073
rs1361857,0.004761,0.001465,0.040066,0.001681,0.004098,-0.002924,-0.020101,0.011855,0.000152,0.014623,...,0.099855,0.157009,0.689702,0.692892,0.817535,0.311690,0.344827,0.797607,0.999000,0.972940
rs1361858,-0.003334,0.007506,0.031143,0.005593,0.008060,0.002920,-0.018919,0.004641,0.006147,-0.000197,...,0.087363,0.174945,0.679124,0.682407,0.829352,0.352732,0.346324,0.769073,0.972940,0.999000

In [30]:
summary_stats = pd.DataFrame(LD_pearson_corr.apply(lambda row: (row ** 2).sum(), axis=1))

In [32]:
summary_stats.columns = ['LD_r_squared']

In [39]:
summary_stats['beta_marginal'] = beta_marg['V1'] ** 2

In [40]:
summary_stats

            LD_r_squared  beta_marginal
rs9518832      19.018036       0.000345
rs970028       22.803768       0.001638
rs12866357     15.921600       0.001008
rs9518903      21.868259       0.004220
rs9518907      22.776351       0.001450
...                  ...            ...
rs17785193      7.369414       0.000153
rs6560554       7.720214       0.000032
rs1361856       9.490617       0.000240
rs1361857       9.631004       0.000547
rs1361858       9.523615       0.000640

[4268 rows x 2 columns]

In [38]:
M = 4268 # Number of SNPs
N = 1000 # Number of Individuals

In [43]:
LD_r_squared_mean = summary_stats['LD_r_squared'].values.mean()

In [44]:
LD_r_squared_mean

23.113001447834257

In [45]:
beta_marginal_mean = summary_stats['beta_marginal'].values.mean()

In [46]:
beta_marginal_mean

0.0020457284056866485

In [49]:
summary_stats['diff_beta'] = summary_stats['beta_marginal'] - beta_marginal_mean

In [52]:
summary_stats['diff_LD_r_squared'] = summary_stats['LD_r_squared'] - LD_r_squared_mean

In [53]:
summary_stats

            LD_r_squared  beta_marginal  diff_beta  diff_LD_r_squared
rs9518832      19.018036       0.000345  -0.001701          -4.094965
rs970028       22.803768       0.001638  -0.000408          -0.309234
rs12866357     15.921600       0.001008  -0.001038          -7.191402
rs9518903      21.868259       0.004220   0.002175          -1.244742
rs9518907      22.776351       0.001450  -0.000596          -0.336651
...                  ...            ...        ...                ...
rs17785193      7.369414       0.000153  -0.001893         -15.743587
rs6560554       7.720214       0.000032  -0.002013         -15.392787
rs1361856       9.490617       0.000240  -0.001806         -13.622385
rs1361857       9.631004       0.000547  -0.001499         -13.481998
rs1361858       9.523615       0.000640  -0.001406         -13.589387

[4268 rows x 4 columns]

In [54]:
expected_beta = summary_stats['diff_beta'].sum()
expected_LD = summary_stats['diff_LD_r_squared'].sum()

In [55]:
heritability = expected_beta *M / expected_LD *N

In [56]:
heritability

-246.0259331597222

In [57]:
summary_stats['betaLD'] = summary_stats['beta_marginal'] * summary_stats['LD_r_squared']

In [58]:
sum_beta_sq_ld = summary_stats['betaLD'].sum()

In [59]:
sum_ld = summary_stats['LD_r_squared'].sum()

In [60]:
summary_stats['LD_squared'] = summary_stats['LD_r_squared'] **2

In [61]:
sum_ld_sq = summary_stats['LD_squared'].sum()

In [62]:
heritability = M * ((N * sum_beta_sq_ld - sum_ld) / (N * sum_ld_sq))

In [63]:
heritability

0.19017122782624732

In [ ]:
# https://web.ma.utexas.edu/users/m408m/Display14-7-5.shtml