Note to Grader: Due to errors in loading gzip data, I have uncompressed csv before loading. If you are unable to regenerate results please contact me at keval.pipalia@mail.mcgill.ca, I manage dependency for each assignment using poetry so I can share the poetry.lock file for regeneration.

## Question 1 [2%] Implementing LD score regression

For a phenotype of interest, we have collected the marginal statistics β ̃ for M = 4268 SNPs and the M × M LD matrix R (i.e., pairwise SNP-SNP Pearson correlation). The marginal statistics are based on N = 1000 individuals. Download the marginal statistics and LD matrix from here:
https://drive.google.com/drive/folders/1tq4bTdbsv1iwO4wHxq1smzoN9D5luapp?usp=sharing
For this question, you may also assume there is no population stratification in this dataset. Both phenotype and genotype were standardized.
Implement the very basic LD score regression algorithm with a programming language of your choice (preferably Python or R) to estimate the heritability of the phenotype.
What’s your estimate of the heritability?
Submit your answer to this question in iPython notebook with name COMP565 A1 ldsr.ipynb
or R Markdown COMP565 A1 ldsr.Rmd on MyCourses. This way the TA can run your code to validate its output. Do not submit the data provided to you as long as you have the clear path to the data you run.

## Solution

#### Given data is stored under following structure: `./data/Q1/`

In [1]:
import pandas as pd

In [2]:
M = 4268 # Number of SNPs
N = 1000 # Number of Individuals

In [3]:
# Please notice the path difference, also I was getting some errors loading gzip directly so, I am using uncompressed versions of file.
# If you are using linux you can use `gzip -d filename` to uncompress files.
LD_pearson_corr = pd.read_csv('data/Q1/LD.csv', index_col=0)

In [4]:
# Please notice the path difference, also I was getting some errors loading gzip directly so, I am using uncompressed versions of file.
# If you are using linux you can use `gzip -d filename` to uncompress files.
beta_marg = pd.read_csv('data/Q1/beta_marginal.csv', index_col=0)

In [5]:
LD_pearson_corr

,rs9518832,rs970028,rs12866357,rs9518903,rs9518907,rs9518940,rs9518943,rs9300794,rs9586099,rs1158176,...,rs12004116,rs10781386,rs10119153,rs1936285,rs12685440,rs17785193,rs6560554,rs1361856,rs1361857,rs1361858
rs9518832,0.999000,-0.647595,0.528240,-0.658121,-0.646243,-0.647858,-0.154406,0.847165,-0.648272,0.552677,...,0.008973,-0.011053,0.054921,0.058127,0.033414,-0.032973,-0.023526,0.005402,0.004761,-0.003334
rs970028,-0.647595,0.999000,-0.409308,0.956043,0.997054,0.994144,-0.431340,-0.689275,0.998028,-0.567007,...,0.000139,0.046088,-0.013413,-0.018185,-0.018804,-0.003368,-0.018899,0.021746,0.001465,0.007506
rs12866357,0.528240,-0.409308,0.999000,-0.430109,-0.408672,-0.402608,-0.135176,0.577297,-0.409626,0.313646,...,-0.013543,-0.005163,0.071111,0.072883,0.048066,-0.031056,-0.018028,0.034910,0.040066,0.031143
rs9518903,-0.658121,0.956043,-0.430109,0.999000,0.958079,0.950806,-0.458652,-0.697505,0.955032,-0.505016,...,0.000919,0.039405,-0.012052,-0.016538,-0.025780,-0.019289,-0.029027,0.027833,0.001681,0.005593
rs9518907,-0.646243,0.997054,-0.408672,0.958079,0.999000,0.992196,-0.430434,-0.688063,0.996088,-0.565783,...,0.001113,0.048371,-0.011241,-0.016031,-0.018444,-0.006520,-0.018030,0.024149,0.004098,0.008060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
rs17785193,-0.032973,-0.003368,-0.031056,-0.019289,-0.006520,-0.001655,0.036886,-0.018916,-0.003838,-0.042768,...,0.336696,0.045058,-0.156078,-0.154978,0.373735,0.999000,0.924057,-0.156567,0.311690,0.352732
rs6560554,-0.023526,-0.018899,-0.018028,-0.029027,-0.018030,-0.016807,0.030973,-0.000108,-0.019333,-0.035660,...,0.377046,0.049715,-0.161920,-0.160869,0.347391,0.924057,0.999000,-0.159996,0.344827,0.346324
rs1361856,0.005402,0.021746,0.034910,0.027833,0.024149,0.020495,-0.031700,-0.006015,0.022834,0.012648,...,-0.089486,0.178569,0.848165,0.851054,0.713453,-0.156567,-0.159996,0.999000,0.797607,0.769073
rs1361857,0.004761,0.001465,0.040066,0.001681,0.004098,-0.002924,-0.020101,0.011855,0.000152,0.014623,...,0.099855,0.157009,0.689702,0.692892,0.817535,0.311690,0.344827,0.797607,0.999000,0.972940
rs1361858,-0.003334,0.007506,0.031143,0.005593,0.008060,0.002920,-0.018919,0.004641,0.006147,-0.000197,...,0.087363,0.174945,0.679124,0.682407,0.829352,0.352732,0.346324,0.769073,0.972940,0.999000

In [6]:
beta_marg

                  V1
rs9518832  -0.018577
rs970028    0.040470
rs12866357 -0.031741
rs9518903   0.064965
rs9518907   0.038076
...              ...
rs17785193 -0.012362
rs6560554  -0.005701
rs1361856   0.015481
rs1361857   0.023380
rs1361858   0.025291

[4268 rows x 1 columns]

We can solve this regression problem through multiple way, we will use the simplest and intuitive analytical way of using calculus. Motivations for this approach can be found here: https://web.ma.utexas.edu/users/m408m/Display14-7-5.shtml

In [7]:
summary_stats = pd.DataFrame()

In [8]:
summary_stats['LD_score'] = LD_pearson_corr.apply(lambda row: (row**2).sum(), axis=1)

In [9]:
summary_stats['beta'] = beta_marg['V1']**2

In [10]:
summary_stats

             LD_score      beta
rs9518832   19.018036  0.000345
rs970028    22.803768  0.001638
rs12866357  15.921600  0.001008
rs9518903   21.868259  0.004220
rs9518907   22.776351  0.001450
...               ...       ...
rs17785193   7.369414  0.000153
rs6560554    7.720214  0.000032
rs1361856    9.490617  0.000240
rs1361857    9.631004  0.000547
rs1361858    9.523615  0.000640

[4268 rows x 2 columns]

In [11]:
sum_beta_LD = (summary_stats['beta'] * summary_stats['LD_score']).sum()

In [12]:
sum_LD = summary_stats['LD_score'].sum()

In [13]:
sum_LD_squared = (summary_stats['LD_score']**2).sum()

In [14]:
heritability = M * ((N * sum_beta_LD - sum_LD) / (N * sum_LD_squared))

In [15]:
print("Estimated Heritability: ", heritability)

Estimated Heritability:  0.19017122782624732